services:
  app:
    build: .
    container_name: kargo_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - mailpit

  db:
    image: mysql:8.0
    container_name: kargo_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kargo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    container_name: kargo_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kargo_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: